parameters:
    plugin.help:
        prefix: '@@npbot'

    plugin.status:
        prefix: '@@npbot'

services:
    plugin.help:
        class: Nopolabs\Yabot\Plugins\HelpPlugin
        arguments:
            - '@message.dispatcher'
            - '@logger'
            - '@yabot'
        tags:
            - { name: yabot.plugin }

    plugin.status:
        class: Nopolabs\Yabot\Plugins\StatusPlugin
        arguments:
            - '@message.dispatcher'
            - '@logger'
            - '@yabot'
        tags:
            - { name: yabot.plugin }
