services:
    plugin.messagelog:
        class: Nopolabs\Yabot\Plugin\MessageLogPlugin
        arguments:
            - '@logger'
            - '@yabot'
        tags:
            - { name: yabot.plugin }