parameters:

services:
    plugin.status:
        class: Nopolabs\Yabot\Status\StatusPlugin
        arguments:
            - '@message.dispatcher'
            - '@logger'
        tags:
            - { name: yabot.plugin }
